### ISSUE TITLE
problem about results

### ISSUE THREAD

**Issue by 964922903** [CCQC/PES-Learn#17]
Dear author,
When the keyword in my input.out is:
___________________________________________
...
...
# ML-relevant keywords
ml_model = 'nn'   
...
...
______________________________________________
That is, when I select  neural network, the fitted output file is different from Gaussian regression.

The output files of Gaussian regression are: compute_energy.py  hyperparameters  model.json  performance and so on

but  output files of   neural network are ; hyperparameters  model.pt  PES.dat  test_set  train_set
Are these correct? Do not have "performance"
if correct
How should I use the NN model?
like using  the GP model,  have an instance on this webpage:

https://github.com/CCQC/PES-Learn/blob/master/1_Tutorials/0_water_pes_command_line_interface/cli_tutorial.md

"The **_compute_energy.py_** file can be imported and used. Here's an **_example_** python script **_use_model.py_** which imports the pes function and evaluates some energies at some cartesian geometries."

Thanks for your help!!!

**Comment by adabbott** [comment]
The **compute_energy.py** file for neural networks is not quite finished. I will add it in the next few days. Once the change is applied, you will have to **git pull** to update PES-Learn. To generate the convenience function, you will likely have to train a new model. Sorry about that!

**Comment by adabbott** [comment]
Should be fixed now. Trained NN's now produce **compute_energy.py**, and **performance** files.
